### ISSUE TITLE
Fix Kernel system type error when hitting enter upon boot

### ISSUE THREAD

**Issue by bkuhlmann** [AlexB52/retest#240]
## Why

Hello. :wave: I'm seeing an issue where upon initial launch of `retest` -- and hitting <kbd>ENTER</kbd> -- will cause the following exception:

``` 
Setup identified: [RSPEC]. Using command: 'bin/rspec <test>'
Watcher: [LISTEN]
Launching Retest...
Ready to refactor! You can make file changes now

Type interactive command and press enter. Enter 'h' for help.
>
Running last command: ''

/Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/lib/retest/runner.rb:88:in 'Kernel#system': no implicit conversion of nil into String (TypeError)

      result = system(command) ? :tests_pass : :tests_fail
                      ^^^^^^^
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/lib/retest/runner.rb:88:in 'Retest::Runner#system_run'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/lib/retest/runner.rb:18:in 'Retest::Runner#run_last_command'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/3.4.0/forwardable.rb:240:in 'Retest::Program#run_last_command'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:100:in 'Object#run_command'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:136:in 'block (2 levels) in <top (required)>'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:134:in 'Array#each'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:134:in 'block in <top (required)>'
	from <internal:kernel>:168:in 'Kernel#loop'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:128:in '<top (required)>'
	from /var/folders/yn/zk8yhvr1593bbyy_v77zjmg00000gn/T/frum_1678_1735397815355/bin/retest:25:in 'Kernel#load'
	from /var/folders/yn/zk8yhvr1593bbyy_v77zjmg00000gn/T/frum_1678_1735397815355/bin/retest:25:in '<main>'
```

## How

To recreate, launch `retest` in any project and immediately hit <kbd>ENTER</kbd> to recreate the above. The workaround is to run `ra` from the `restest` command prompt to _seed_ it with information and the problem goes away. This _only_ happens upon initial launch.

I'm guessing you'd want to ensure the `command` being passed to `system` defaults to `ra` as that is the default behavior when hitting <kbd>ENTER</kbd> once `retest` is fully initialized.

## Notes

- **Operating System**: macOS 15.2
- **Ruby**: ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +YJIT +PRISM [arm64-darwin24.2.0]
- **Retest**: 2.0.0

**Comment by AlexB52** [comment]
Sorry for the late reply, I just saw that today and didn't receive an email. Not sure what's going on. 

Thanks @bkuhlmann,
I can reproduce the issue and it should be an easy fix. I will push a patch once I get around it (probably before the end of next week)

**Comment by AlexB52** [comment]
@bkuhlmann 

[I've released v2.0.1 ](https://rubygems.org/gems/retest)

The behaviour now is to run the launching command if it does not include placeholders like `<test>` or `<changed>`. Pressing Enter when starting retest as `retest --all` or `retest 'bin/rails test'` or `retest 'ruby filename.rb'` will run the said command. 

If retest is launched with placeholders like `retest 'ruby <changed>'` or `retest --rails` or `retest 'bin/rails test <test>'` , pressing Enter will print the error `Error - Not enough information to run a command. Please trigger a run first.`

**Comment by bkuhlmann** [comment]
Thanks! Ah, OK, I've been using `retest` to only launch but I've updated my alias to use `retest -all` to ensure Retest is properly *seeded* so I don't get the error.

**Comment by AlexB52** [comment]
Yup the default behaviour is to run a single matching file and the --all option should be used if you can run the whole test suite locally. Thanks for reporting the issue.
